### ISSUE TITLE
Skill and Interest proba improving 

### ISSUE THREAD

**Issue by Florian-DELRIEU** [Wolves-SoftWare/SpaceColony#3]
https://github.com/Wolves-SoftWare/SpaceColony/blob/f30a4e3e72218facdc6e72f725d117be24c554d4/src/Gen/Colonist.js#L56-L59

- [x] Augmenter la proba qu'une Stat soit plus proche de 8
- [x] Proba pour intérêt plus proche de 0 ou 1 
- [x] xp exponentielle douce en fonction du level

**Comment by zechaos031** [comment]
✅ Mise a jour de la fonction [choice](https://github.com/Wolves-SoftWare/SpaceColony/blob/dc8ca837d198d4d55b8f38ecd0121fc58984f790/src/Utils/Utils.js#L8)
- Ajout de l'option arrayData de faire en sorte que la liste soit un array d'arrays
- Ajout de getAll qui permet de retourné l'array au lieux d'un nombre

♻️ Si  `weight` est vide ou qu'il manque des index a weight par rapport a la liste rajouté 1 (en cours)

**Comment by zechaos031** [comment]
Tous est fix [ici](https://github.com/Wolves-SoftWare/SpaceColony/compare/dc8ca837d198...497cee8db4ce)

✅ Si  `weight` est vide ou qu'il manque des index a weight par rapport a la liste rajouté 1 (en cours)
