### ISSUE TITLE
JSON Start system save

### ISSUE THREAD

**Issue by zechaos031** [Wolves-SoftWare/SpaceColony#6]
Faire une sauvegarde plus dans ce style la 
 
```json
{
  "class": "",
  "numberOrbit": "",
  "planet": [
    {
      "type": "",
      "distance": "",
      "orbit": "",
      "moons": [
        {
          "type": ""
        }
      ],
      "ring": []
    }
  ],
  "asteroid": [
    {
      "type": "",
      "distance": "",
      "orbit": ""
    }
  ],
  "stars": [
    {
      "type": ""
    }
  ]
}
```

- [ ] fix https://github.com/Wolves-SoftWare/SpaceColony/issues/6#issuecomment-956503143

**Comment by zechaos031** [comment]
et 1 JSON est egale a un system solaire

**Comment by Florian-DELRIEU** [comment]
https://github.com/Wolves-SoftWare/SpaceColony/blob/0fa1d8703346ed6901c9b2ffefd703db803c214a/src/coc_testinghall/testJSON.py#L34-L51

- [ ] delete `Line 45`
- [ ] Move `return` to condition loop `Line 44`
